core:
    resource:
        path: ../src/Core/Controller/
        namespace: App\Core\Controller
    type: attribute
    
game:
    resource:
        path: ../src/Game/Controller/
        namespace: App\Game\Controller
    type: attribute
    
monster_compendium:
    resource:
        path: ../src/MonsterCompendium/Controller/
        namespace: App\MonsterCompendium\Controller
    type: attribute
    
authentication:
    resource:
        path: ../src/Authentication/Controller/
        namespace: App\Authentication\Controller
    type: attribute
